import { Rule } from './types';

export const mockRules: Rule[] = [
  {
    id: '3119',
    name: '(T+1)通用语句--编码不存在pub201',
    fieldName: 'F013V_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/8/16 16:43:43',
  },
  {
    id: '3120',
    name: '(T+1)通用语句--机构ID不存在PUB203',
    fieldName: 'F001V_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/8/16 16:43:43',
  },
  {
    id: '79236',
    name: '(T+1)STK487-报表类型不存在pub201',
    fieldName: 'F006V_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/11/23 10:49:55',
  },
  {
    id: '79237',
    name: '(T+1)STK487-合计项多加工',
    fieldName: 'F011V_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/11/23 10:49:55',
  },
  {
    id: '79238',
    name: '(T+1)STK487-合计值与127对比单位错误 (HB)',
    fieldName: 'F012N_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/11/23 10:49:55',
  },
  {
    id: '79239',
    name: '(T+1)STK487-合计值与127对比单位错误 (HBTZ)',
    fieldName: 'F012N_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '可疑错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/11/23 10:49:55',
  },
  {
    id: '79240',
    name: '(T+1)STK487-项目公布名称为空错误',
    fieldName: 'F010V_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/11/23 10:49:55',
  },
];
