import { Rule } from './types';

export const mockRules: Rule[] = [
  {
    id: '3119',
    name: '(T+1)通用语句--编码不存在pub201',
    fieldName: 'F013V_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/8/16 16:43:43',
  },
  {
    id: '3120',
    name: '(T+1)通用语句--机构ID不存在PUB203',
    fieldName: 'F001V_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/8/16 16:43:43',
  },
  {
    id: '79236',
    name: '(T+1)STK487-报表类型不存在pub201',
    fieldName: 'F006V_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/11/23 10:49:55',
  },
  {
    id: '79237',
    name: '(T+1)STK487-合计项多加工',
    fieldName: 'F011V_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/11/23 10:49:55',
  },
  {
    id: '79238',
    name: '(T+1)STK487-合计值与127对比单位错误 (HB)',
    fieldName: 'F012N_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/11/23 10:49:55',
  },
  {
    id: '79239',
    name: '(T+1)STK487-合计值与127对比单位错误 (HBTZ)',
    fieldName: 'F012N_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '可疑错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/11/23 10:49:55',
  },
  {
    id: '79240',
    name: '(T+1)STK487-项目公布名称为空错误',
    fieldName: 'F010V_STK487',
    groupCategory: '国财-A股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/11/23 10:49:55',
  },
  {
    id: '79241',
    name: '(T+1)STK487-公告日期晚于当前日期',
    fieldName: 'F001D_STK487',
    groupCategory: '国财-A股组',
    priority: 3,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/11/23 10:50:55',
  },
  {
    id: '79242',
    name: '(T+1)STK487-项目公布名称格式异常',
    fieldName: 'F010V_STK487',
    groupCategory: '国财-A股组',
    priority: 3,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '可疑错误',
    status: '正常',
    isValid: true,
    author: '关玉阁',
    createdAt: '2023/11/23 10:51:55',
  },
  {
    id: '79243',
    name: '(T+1)STK487-备注字段格式异常',
    fieldName: 'F020V_STK487',
    groupCategory: '国财-A股组',
    priority: 2,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '可疑错误',
    status: '正常',
    isValid: true,
    author: '李明',
    createdAt: '2023/11/24 09:11:22',
  },
  {
    id: '79244',
    name: '(T+1)STK487-创建日期小于合理范围',
    fieldName: 'F021D_STK487',
    groupCategory: '国财-A股组',
    priority: 3,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '李明',
    createdAt: '2023/11/24 09:15:22',
  },
  {
    id: '81201',
    name: '(T+1)债券-发行人机构ID不存在PUB203',
    fieldName: 'F001V_BND101',
    groupCategory: '债券组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '王蕾',
    createdAt: '2024/1/8 13:20:10',
  },
  {
    id: '81202',
    name: '(T+1)债券-到期日期早于发行日期',
    fieldName: 'F012D_BND101',
    groupCategory: '债券组',
    priority: 2,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '王蕾',
    createdAt: '2024/1/8 13:22:10',
  },
  {
    id: '83001',
    name: '(T+1)基金-基金代码为空',
    fieldName: 'F001V_FUND',
    groupCategory: '基金组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '陈洁',
    createdAt: '2024/2/18 11:02:00',
  },
  {
    id: '83002',
    name: '(T+1)基金-净值日期格式异常',
    fieldName: 'F008D_FUND',
    groupCategory: '基金组',
    priority: 3,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '可疑错误',
    status: '正常',
    isValid: true,
    author: '陈洁',
    createdAt: '2024/2/18 11:05:00',
  },
  {
    id: '85001',
    name: '(T+1)港股-证券代码不存在',
    fieldName: 'F002V_HK',
    groupCategory: '港股组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '赵林',
    createdAt: '2024/3/6 15:42:00',
  },
  {
    id: '85002',
    name: '(T+1)港股-交易币种编码不存在',
    fieldName: 'F013V_HK',
    groupCategory: '港股组',
    priority: 3,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '赵林',
    createdAt: '2024/3/6 15:45:00',
  },
  {
    id: '86001',
    name: '(T+1)研报-标题为空',
    fieldName: 'F003V_RPT',
    groupCategory: '研报组',
    priority: 2,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '周宁',
    createdAt: '2024/4/2 10:00:00',
  },
  {
    id: '86002',
    name: '(T+1)研报-发布日期晚于当前日期',
    fieldName: 'F009D_RPT',
    groupCategory: '研报组',
    priority: 3,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '周宁',
    createdAt: '2024/4/2 10:03:00',
  },
  {
    id: '87001',
    name: '(T+1)指数-指数代码为空',
    fieldName: 'F001V_IDX',
    groupCategory: '指数组',
    priority: 4,
    qualityType: '规则质检',
    debugStatus: '未调试',
    errorType: '肯定错误',
    status: '正常',
    isValid: true,
    author: '吴迪',
    createdAt: '2024/5/12 16:12:00',
  },
];
